server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:aau-claaudia/config.git
          defaultLabel: main
          ignoreLocalSshSettings: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEA6g1TRNMeNnSPRVxI7wQgqUhYdNyZhrDwO963jg4IJKSJKhjK
            DENNENØGLEERGÅETISTYKKERSÅDUKANIKKEBRUGEDENTILNOGETSOMHELSTALTSÅ
            Sc43HMlu7nXMD41SZdh/1J70Jzz0ljVB2MGA4WaC8tPrKqtNJaNGS+ir7QDH/w==
            -----END RSA PRIVATE KEY-----

logging:
  level:
    org:
      springframework:
        cloud:
          config: DEBUG
